-- MySQL Script generated by MySQL Workbench
-- Mon Jun 12 15:31:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema opticaculodebotella
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `opticaculodebotella` ;

-- -----------------------------------------------------
-- Schema opticaculodebotella
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `opticaculodebotella` DEFAULT CHARACTER SET utf8mb3 ;
USE `opticaculodebotella` ;

-- -----------------------------------------------------
-- Table `opticaculodebotella`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticaculodebotella`.`clientes` (
  `idClientes` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Codigo Postal` INT NOT NULL,
  `Telefono` INT NOT NULL,
  `Correo electrónico` VARCHAR(45) NOT NULL,
  `Fecha de registro` DATE NOT NULL,
  `Recomendado por` VARCHAR(25) NULL DEFAULT NULL,
  `Atendido por` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `opticaculodebotella`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticaculodebotella`.`proveedor` (
  `idProveedor` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Teléfono` INT NOT NULL,
  `Fax` INT NULL DEFAULT NULL,
  `NIF` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `opticaculodebotella`.`tipodemontura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticaculodebotella`.`tipodemontura` (
  `idTipoDeMontura` INT NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idTipoDeMontura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `opticaculodebotella`.`anteojos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticaculodebotella`.`anteojos` (
  `idAnteojos` INT NOT NULL,
  `TipoDeMontura_idTipoDeMontura` INT NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  `Marca` VARCHAR(15) NOT NULL,
  `Graduación` VARCHAR(15) NOT NULL,
  `Color de montura` VARCHAR(25) NOT NULL,
  `Color de cada vidrio` VARCHAR(25) NOT NULL,
  `Precio` INT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idAnteojos`),
  CONSTRAINT `fk_Anteojos_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `opticaculodebotella`.`clientes` (`idClientes`),
  CONSTRAINT `fk_Anteojos_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `opticaculodebotella`.`proveedor` (`idProveedor`),
  CONSTRAINT `fk_Anteojos_TipoDeMontura1`
    FOREIGN KEY (`TipoDeMontura_idTipoDeMontura`)
    REFERENCES `opticaculodebotella`.`tipodemontura` (`idTipoDeMontura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_Anteojos_TipoDeMontura1_idx` ON `opticaculodebotella`.`anteojos` (`TipoDeMontura_idTipoDeMontura` ASC) VISIBLE;

CREATE INDEX `fk_Anteojos_Proveedor1_idx` ON `opticaculodebotella`.`anteojos` (`Proveedor_idProveedor` ASC) VISIBLE;

CREATE INDEX `fk_Anteojos_Clientes1_idx` ON `opticaculodebotella`.`anteojos` (`Clientes_idClientes` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `opticaculodebotella`.`dirección`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticaculodebotella`.`dirección` (
  `idDirección` INT NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  `Calle` VARCHAR(35) NOT NULL,
  `Número` INT NOT NULL,
  `Piso` INT NOT NULL,
  `Puerta` INT NOT NULL,
  `Ciudad` VARCHAR(30) NOT NULL,
  `Codigo postal` INT NOT NULL,
  `País` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idDirección`),
  CONSTRAINT `fk_Dirección_Proveedor`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `opticaculodebotella`.`proveedor` (`idProveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_Dirección_Proveedor_idx` ON `opticaculodebotella`.`dirección` (`Proveedor_idProveedor` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

/*total de facturas de un cliente en un periodo determinado*/
SELECT * FROM clientes WHERE 'Fecha de registro' = '2023-06-12';

/*diferentes modelos de anteojos vendidos por un empleado en un periodo de un año*/
SELECT * FROM clientes WHERE 'Atendido por' = 'Jesus' AND 'Fecha de registro' BETWEEN '2022-06-12' AND '2023-06-12';

/*Lista de proveedores que han vendido anteojos con exito en la optica*/
SELECT * FROM anteojos;

